kind: ConfigMap  
apiVersion: v1  
metadata:  
  name: configmap-{{ .Files.Get "config/config.json" | regexFind "\\d+\\.\\d+\\.\\d+" }}
  labels:
    version:  {{ .Files.Get "config/config.json" | regexFind "\\d+\\.\\d+\\.\\d+" }}   
data:  
  config.json: | {{ range .Files.Lines "config/config.json" }}
    {{ . }}{{ end }}
