apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "dexcare.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 1
        args:
        - name: service-name
          value: {{ include "dexcare.fullname" . }}.demo.svc.cluster.local
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
       {{- include "dexcare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dexcare.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx"
          name: vol
      volumes:
        - name: vol
          configMap:
             name:  configmap-{{ .Files.Get "config/config.json" | regexFind "\\d+\\.\\d+\\.\\d+" }}
