apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dexcare.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       {{- include "dexcare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dexcare.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx"
          name: vol
      volumes:
        - name: vol
          configMap:
             name:  configmap-{{ .Files.Get "config/config.json" | regexFind "\\d+\\.\\d+\\.\\d+" }}
